on:
  pull_request:
  push:
    branches: [main]

jobs:
  lints:
    name: Build & Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix build . --print-build-logs
      - run: nix flake check . --print-build-logs